package com.novelai.lanstudio;

public final class OfflineGalleryPage {
    private OfflineGalleryPage() {
    }

    public static String html() {
        return """
            <!doctype html>
            <html lang="ko">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
              <title>오프라인 갤러리</title>
              <style>
                :root{color-scheme:dark;--bg:#090a12;--panel:#121421;--line:rgba(255,255,255,.10);--text:#f3f4fb;--muted:#9598aa;--accent:#8274ff;--cyan:#4bd7ef}
                *{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,"Noto Sans KR",sans-serif}button,a{font:inherit}
                body{padding:calc(18px + env(safe-area-inset-top)) 14px calc(28px + env(safe-area-inset-bottom))}
                header{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin:0 auto 16px;max-width:1040px}.eyebrow{display:block;color:#a79dff;font-size:10px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}h1{margin:7px 0 5px;font-size:25px;line-height:1.15}.sync{margin:0;color:var(--muted);font-size:11px}.header-actions{display:flex;align-items:center;gap:7px}.theme-toggle{width:34px;height:34px;border:1px solid var(--line);border-radius:10px;padding:0;background:rgba(255,255,255,.035);color:#a79dff}.offline-badge{flex:none;border:1px solid rgba(75,215,239,.3);border-radius:999px;padding:7px 10px;background:rgba(75,215,239,.08);color:#9beaf5;font-size:10px;font-weight:750}
                .toolbar{position:sticky;top:calc(6px + env(safe-area-inset-top));z-index:5;max-width:1040px;margin:0 auto 14px;padding:5px;display:grid;grid-template-columns:1fr 1fr;gap:5px;border:1px solid var(--line);border-radius:14px;background:rgba(13,15,26,.94);backdrop-filter:blur(12px)}.toolbar button{min-height:43px;border:0;border-radius:10px;background:transparent;color:var(--muted);font-weight:750}.toolbar button.active{background:#292640;color:white}.toolbar small{margin-left:5px;color:#aaa5d9}
                .grid{max-width:1040px;margin:auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.card{min-width:0;border:1px solid var(--line);border-radius:15px;overflow:hidden;background:var(--panel);box-shadow:0 12px 28px rgba(0,0,0,.18)}.open{width:100%;aspect-ratio:1;border:0;padding:0;background:#05060a;display:block;overflow:hidden}.open img{display:block;width:100%;height:100%;object-fit:cover}.card-copy{padding:9px}.dimensions{color:var(--muted);font-size:9px}.tags{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}.tag{max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:1px solid rgba(130,116,255,.26);border-radius:999px;padding:4px 7px;background:rgba(130,116,255,.08);color:#c9c5ff;font-size:9px}.card-actions{margin-top:9px;padding-top:8px;border-top:1px solid var(--line);display:flex;justify-content:flex-end}.card-download{min-height:34px;border:1px solid rgba(130,116,255,.38);border-radius:9px;padding:0 11px;background:rgba(130,116,255,.1);color:#d4d0ff;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;font-size:10px;font-weight:800}.empty{grid-column:1/-1;margin-top:70px;text-align:center;color:var(--muted)}
                .viewer[hidden]{display:none}.viewer{position:fixed;inset:0;z-index:50;background:rgba(2,3,7,.98);display:grid;grid-template-rows:minmax(0,1fr) auto;padding:env(safe-area-inset-top) 0 env(safe-area-inset-bottom)}.stage{position:relative;min-width:0;min-height:0;overflow:hidden;display:grid;place-items:center;touch-action:none;user-select:none}.viewer-image{display:block;width:100%;height:100%;object-fit:contain;transform-origin:center;will-change:transform;filter:drop-shadow(0 22px 58px rgba(0,0,0,.65))}.viewer-control{position:absolute;z-index:4;border:1px solid rgba(255,255,255,.16);background:rgba(14,16,27,.82);color:white;backdrop-filter:blur(10px)}.close{left:12px;top:calc(12px + env(safe-area-inset-top));width:42px;height:42px;border-radius:12px}.nav{top:50%;width:40px;height:58px;border-radius:12px;transform:translateY(-50%);font-size:28px}.nav.previous{left:10px}.nav.next{right:10px}.nav:disabled{opacity:.18}.viewer.zoomed .nav{opacity:0;pointer-events:none}.counter{position:absolute;right:12px;top:calc(14px + env(safe-area-inset-top));z-index:4;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:6px 9px;background:rgba(14,16,27,.78);font-size:10px}.zoom-hint{position:absolute;left:50%;bottom:12px;z-index:4;transform:translateX(-50%);white-space:nowrap;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:7px 10px;background:rgba(14,16,27,.78);color:#c6c8d6;font-size:9px;pointer-events:none}
                .viewer-footer{border-top:1px solid var(--line);padding:12px 14px calc(12px + env(safe-area-inset-bottom));background:#10121d;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px}.viewer-footer .tags{margin:0}.download{min-height:42px;border:1px solid rgba(130,116,255,.45);border-radius:11px;padding:0 15px;background:rgba(130,116,255,.14);color:#ddd9ff;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;font-size:11px;font-weight:800}
                :root[data-theme=light]{color-scheme:light;--bg:#f3eee4;--panel:#fffaf2;--line:transparent;--text:#302b25;--muted:#746b60;--accent:#7564c3;--cyan:#2f7d76}:root[data-theme=light] body{background:radial-gradient(circle at 88% 0,rgba(202,151,88,.14),transparent 28rem),var(--bg)}:root[data-theme=light] .toolbar{background:rgba(248,243,234,.96)}:root[data-theme=light] .toolbar button.active{background:#e8dfd2;color:#4d426f}:root[data-theme=light] .theme-toggle{background:rgba(91,70,48,.055);color:#5f50a8}:root[data-theme=light] .offline-badge{color:#2f7d76}:root[data-theme=light] .tag{color:#5f50a8}:root[data-theme=light] .card-download{color:#5f50a8}:root[data-theme=light] .card{box-shadow:0 12px 28px rgba(83,66,48,.12)}
                body *{border-color:transparent!important}button:focus-visible,a:focus-visible{outline:0;box-shadow:0 0 0 3px rgba(75,215,239,.34)}:root[data-theme=light] button:focus-visible,:root[data-theme=light] a:focus-visible{box-shadow:0 0 0 3px rgba(95,80,168,.3)}
                @media(min-width:600px){.grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.open{aspect-ratio:4/5}.viewer-footer{padding-inline:24px}}
                .export-pair{display:flex;gap:6px;flex-wrap:wrap;width:100%}.export-pair a{flex:1;min-height:44px;min-width:0;padding:8px 4px;text-align:center}.viewer-footer{grid-template-columns:minmax(0,1fr)}.card-actions{justify-content:stretch}
              </style>
            </head>
            <body>
              <header><div><span class="eyebrow">Offline library</span><h1>기기에 저장된 이미지</h1><p id="sync" class="sync">캐시를 읽는 중…</p></div><div class="header-actions"><button id="themeToggle" class="theme-toggle" type="button" aria-label="라이트 모드로 전환">☀</button><span class="offline-badge">읽기 전용</span></div></header>
              <nav class="toolbar" aria-label="보관 위치"><button id="temporaryTab" class="active" type="button">임시 보관 <small id="temporaryCount">0</small></button><button id="favoriteTab" type="button">즐겨찾기 <small id="favoriteCount">0</small></button></nav>
              <main id="grid" class="grid"><p class="empty">캐시를 불러오는 중…</p></main>
              <section id="viewer" class="viewer" hidden aria-label="캐시 이미지 상세 보기">
                <div id="stage" class="stage">
                  <img id="viewerImage" class="viewer-image" alt="캐시된 이미지">
                  <button id="close" class="viewer-control close" type="button" aria-label="닫기">×</button>
                  <button id="previous" class="viewer-control nav previous" type="button" aria-label="이전 이미지">‹</button>
                  <button id="next" class="viewer-control nav next" type="button" aria-label="다음 이미지">›</button>
                  <span id="counter" class="counter"></span>
                  <span id="zoomHint" class="zoom-hint">화면맞춤 · 좌우 이동 · 아래로 닫기</span>
                </div>
                <footer class="viewer-footer"><div id="viewerTags" class="tags"></div><div class="export-pair"><a id="download" class="download" href="#" aria-label="EXIF 보존 다운로드">↓ 정보 보존</a><a id="downloadClean" class="download" href="#" aria-label="EXIF 제거 다운로드">↓ 정보 제거</a></div></footer>
              </section>
              <script>
                const state={all:[],visible:[],folder:'temporary',index:-1,scale:1,x:0,y:0,dragX:0,dragY:0,pointers:new Map(),singleStart:null,panLast:null,pinch:null};
                const themeKey='novelai-lan-studio-theme-v1';let theme=localStorage.getItem(themeKey)==='light'?'light':'dark';function applyTheme(next){theme=next;document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;localStorage.setItem(themeKey,theme);const button=document.getElementById('themeToggle');button.textContent=theme==='dark'?'☀':'☾';button.setAttribute('aria-label',theme==='dark'?'라이트 모드로 전환':'다크 모드로 전환')}applyTheme(theme);document.getElementById('themeToggle').addEventListener('click',()=>applyTheme(theme==='dark'?'light':'dark'));
                const grid=document.getElementById('grid');const viewer=document.getElementById('viewer');const stage=document.getElementById('stage');const viewerImage=document.getElementById('viewerImage');const zoomHint=document.getElementById('zoomHint');
                const temporaryTab=document.getElementById('temporaryTab');const favoriteTab=document.getElementById('favoriteTab');const previous=document.getElementById('previous');const next=document.getElementById('next');
                const imageUrl=id=>'/offline/image/'+encodeURIComponent(id);
                const downloadUrl=(id,mode)=>'novelai-offline-download://image/'+encodeURIComponent(id)+'?metadata='+mode;
                function exportLinks(id){const group=document.createElement('div');group.className='export-pair';for(const [mode,label] of [['preserve','정보 보존'],['remove','정보 제거']]){const a=document.createElement('a');a.className='card-download';a.href=downloadUrl(id,mode);a.textContent='↓ '+label;a.setAttribute('aria-label','EXIF '+label+' 다운로드');group.append(a)}return group}
                function tagNodes(tags,target){target.replaceChildren();for(const name of tags){const tag=document.createElement('span');tag.className='tag';tag.textContent='#'+name;target.append(tag)}if(!tags.length){const empty=document.createElement('span');empty.className='dimensions';empty.textContent='태그 없음';target.append(empty)}}
                function render(){state.visible=state.all.filter(item=>Boolean(item.favorite)===(state.folder==='favorites'));grid.replaceChildren();temporaryTab.classList.toggle('active',state.folder==='temporary');favoriteTab.classList.toggle('active',state.folder==='favorites');for(const item of state.visible){const card=document.createElement('article');card.className='card';const open=document.createElement('button');open.type='button';open.className='open';open.setAttribute('aria-label','이미지 크게 보기');const image=document.createElement('img');image.loading='lazy';image.src=imageUrl(item.id);image.alt=(item.tags||[]).join(', ')||'캐시된 이미지';open.append(image);open.addEventListener('click',()=>openViewer(item.id));const copy=document.createElement('div');copy.className='card-copy';const dimensions=document.createElement('div');dimensions.className='dimensions';dimensions.textContent=item.width+'×'+item.height;const tags=document.createElement('div');tags.className='tags';tagNodes(item.tags||[],tags);const actions=document.createElement('div');actions.className='card-actions';actions.append(exportLinks(item.id));copy.append(dimensions,tags,actions);card.append(open,copy);grid.append(card)}if(!state.visible.length){const empty=document.createElement('p');empty.className='empty';empty.textContent=state.folder==='favorites'?'캐시된 즐겨찾기가 없습니다.':'캐시된 임시 이미지가 없습니다.';grid.append(empty)}}
                function setFolder(folder){if(state.folder===folder)return;closeViewer();state.folder=folder;render()}
                function openViewer(id){state.index=state.visible.findIndex(item=>item.id===id);if(state.index<0)return;viewer.hidden=false;document.body.style.overflow='hidden';showCurrent()}
                function closeViewer(){if(viewer.hidden)return;viewer.hidden=true;document.body.style.overflow='';viewerImage.removeAttribute('src');resetTransform()}
                window.OfflineGalleryBack=()=>{if(viewer.hidden)return false;if(state.scale>1.01)resetTransform();else closeViewer();return true};
                function showCurrent(){const item=state.visible[state.index];if(!item){closeViewer();return}resetTransform();viewerImage.src=imageUrl(item.id);document.getElementById('counter').textContent=(state.index+1)+' / '+state.visible.length;tagNodes(item.tags||[],document.getElementById('viewerTags'));document.getElementById('download').href=downloadUrl(item.id,'preserve');document.getElementById('downloadClean').href=downloadUrl(item.id,'remove');previous.disabled=state.index<=0;next.disabled=state.index>=state.visible.length-1}
                function navigate(direction){if(state.scale>1.01)return;const target=state.index+direction;if(target<0||target>=state.visible.length)return;state.index=target;showCurrent()}
                function clamp(value,min,max){return Math.min(max,Math.max(min,value))}
                function resetTransform(){state.scale=1;state.x=0;state.y=0;state.dragX=0;state.dragY=0;state.pointers.clear();state.singleStart=null;state.panLast=null;state.pinch=null;applyTransform()}
                function applyTransform(){viewerImage.style.transform=`translate3d(${state.x+state.dragX}px,${state.y+state.dragY}px,0) scale(${state.scale})`;const zoomed=state.scale>1.01;viewer.classList.toggle('zoomed',zoomed);zoomHint.textContent=zoomed?state.scale.toFixed(1)+'× · 축소해 화면맞춤으로 돌아가기':'화면맞춤 · 좌우 이동 · 아래로 닫기'}
                function points(){return Array.from(state.pointers.values())}
                function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
                stage.addEventListener('pointerdown',event=>{if(event.target.closest('button,a'))return;stage.setPointerCapture(event.pointerId);state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});const current=points();if(current.length===1){state.singleStart={...current[0]};state.panLast={...current[0]};state.dragX=0;state.dragY=0}else if(current.length===2){state.pinch={distance:Math.max(1,distance(current[0],current[1])),scale:state.scale};state.singleStart=null;state.dragX=0;state.dragY=0}event.preventDefault()});
                stage.addEventListener('pointermove',event=>{if(!state.pointers.has(event.pointerId))return;state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});const current=points();if(current.length>=2){if(!state.pinch)state.pinch={distance:Math.max(1,distance(current[0],current[1])),scale:state.scale};let scale=clamp(state.pinch.scale*distance(current[0],current[1])/state.pinch.distance,1,5);if(scale<1.03){scale=1;state.x=0;state.y=0}state.scale=scale;state.dragX=0;state.dragY=0}else if(current.length===1){const point=current[0];if(state.scale>1.01&&state.panLast){const maxX=stage.clientWidth*(state.scale-1)/2;const maxY=stage.clientHeight*(state.scale-1)/2;state.x=clamp(state.x+point.x-state.panLast.x,-maxX,maxX);state.y=clamp(state.y+point.y-state.panLast.y,-maxY,maxY);state.panLast={...point}}else if(state.singleStart){state.dragX=point.x-state.singleStart.x;state.dragY=point.y-state.singleStart.y}}applyTransform();event.preventDefault()});
                function finishPointer(event){if(!state.pointers.has(event.pointerId))return;state.pointers.delete(event.pointerId);const remaining=points();if(remaining.length===1){state.panLast={...remaining[0]};state.singleStart=null}else if(!remaining.length){if(state.scale<=1.01&&state.singleStart){const dx=state.dragX,dy=state.dragY;if(dy>110&&Math.abs(dy)>Math.abs(dx)*1.12){closeViewer();return}if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.15)navigate(dx<0?1:-1)}state.dragX=0;state.dragY=0;state.singleStart=null;state.panLast=null;state.pinch=null;applyTransform()}event.preventDefault()}
                stage.addEventListener('pointerup',finishPointer);stage.addEventListener('pointercancel',finishPointer);
                stage.addEventListener('dblclick',event=>{if(event.target.closest('button,a'))return;if(state.scale>1.01)resetTransform();else{state.scale=2.5;state.x=0;state.y=0;applyTransform()}event.preventDefault()});
                stage.addEventListener('wheel',event=>{const nextScale=clamp(state.scale-event.deltaY*.002,1,5);state.scale=nextScale<1.03?1:nextScale;if(state.scale===1){state.x=0;state.y=0}applyTransform();event.preventDefault()},{passive:false});
                document.getElementById('close').addEventListener('click',closeViewer);previous.addEventListener('click',()=>navigate(-1));next.addEventListener('click',()=>navigate(1));temporaryTab.addEventListener('click',()=>setFolder('temporary'));favoriteTab.addEventListener('click',()=>setFolder('favorites'));
                document.addEventListener('keydown',event=>{if(viewer.hidden)return;if(event.key==='Escape'){if(state.scale>1.01)resetTransform();else closeViewer()}else if(event.key==='ArrowLeft')navigate(-1);else if(event.key==='ArrowRight')navigate(1)});
                fetch('/offline/metadata.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('cache unavailable');return response.json()}).then(data=>{state.all=Array.isArray(data.items)?data.items:[];state.all.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));const temporary=state.all.filter(item=>!item.favorite).length;const favorites=state.all.length-temporary;document.getElementById('temporaryCount').textContent=temporary;document.getElementById('favoriteCount').textContent=favorites;document.getElementById('sync').textContent=data.last_synced_at?'마지막 동기화 · '+new Date(data.last_synced_at).toLocaleString():'동기화 기록 없음';render()}).catch(()=>{grid.innerHTML='<p class="empty">오프라인 캐시를 읽지 못했습니다.</p>';document.getElementById('sync').textContent='캐시 읽기 실패'});
              </script>
            </body>
            </html>
            """;
    }
}
